name: CD

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
      - name: Install PNPM
        run: npm install -g pnpm
      - name: Install dependencies
        run: pnpm install --frozen-lockfile=false
      - name: Publish
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        run: |
          echo "Version changed: ${{ steps.publish.outputs.old-version }} → ${{ steps.publish.outputs.version }}"
      - name: Deploy
        run: pnpm run deploy
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          target-folder: public
          single-commit: true
